/*
 * This source file was generated by the Gradle 'init' task
 */
package org.scraper;

import java.util.List;

import org.scraper.com.fairyloot.community.FairyLootSite;
import org.scraper.com.fairyloot.community.page.BlogPage;
import org.scraper.com.fairyloot.community.page.BookAnnouncementsPage;
import org.scraper.com.fairyloot.community.page.MainPage;
import org.scraper.com.fairyloot.community.page.BookAnnouncementsPage.BlogPost;

public class App {
    public static void main(String[] args) throws Exception {
        try(FairyLootSite fairylootSite = new FairyLootSite()) {
            MainPage mainPage = fairylootSite.navigate();
            System.out.println(mainPage.title());
            
            BookAnnouncementsPage bookAnnouncementsPage = mainPage.clickBookAnnouncements();
            //System.out.println(bookAnnouncementsPage.title());
            System.out.println(bookAnnouncementsPage.url());
            System.out.println(mainPage.url());
            mainPage.close();

            BlogPost featuredBlogPost = bookAnnouncementsPage.featuredBlogPost();
            System.out.println(featuredBlogPost.title());
            System.out.println(featuredBlogPost.date());

            List<BlogPost> archivedBlogPosts = bookAnnouncementsPage.archivedBlogPosts();
            for(BlogPost post : archivedBlogPosts) {
                System.out.println(post.title());
                System.out.println(post.date());
            }

            BlogPage blogPost = archivedBlogPosts.get(0).navigate();
            System.out.println(blogPost.title());
            System.out.println(blogPost.content());
            blogPost.screenshot();
        }

        System.exit(0);
    }
}
